name: message_and_inquiry_management

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build & Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/real-estate-website-2
          tags: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up environment variables
        run: echo "MY_VARIABLE=Hello, World!" >> $GITHUB_ENV

      - name: Display Environment Variables
        run: |
          echo "MY_VARIABLE: $MY_VARIABLE"
          bash ./samplescript4.sh
