name: message_and_inquiry_management

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build & Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/real-estate-website-2
          tags: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up environment variables
        run: |
          export ENV_FILE_URL="https://raw.githubusercontent.com/Chamixth/real-estate-website-2/main/.env"

  deploy:
    name: Deploy Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST_IP }} > ~/.ssh/known_hosts

      - name: Stop existing containers
        run: ssh ${{ secrets.HOST_USERNAME }}@${{ secrets.HOST_IP }} "cd ${{ secrets.WOR_DIR }}; docker compose down"

      - name: Pull Docker Image
        run: ssh ${{ secrets.HOST_USERNAME }}@${{ secrets.HOST_IP }} "cd ${{ secrets.WOR_DIR }}; docker compose pull"

      - name: Start new containers
        run: ssh ${{ secrets.HOST_USERNAME }}@${{ secrets.HOST_IP }} "cd ${{ secrets.WOR_DIR }}; docker compose up -d"

      - name: Cleanup SSH Keys
        run: rm -rf ~/.ssh
