name: message_and_inquiry_management

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate API Documentation
        run: |
          # Downloading the swagger client
          wget https://github.com/swaggo/swag/releases/download/v1.7.0/swag_1.7.0_Linux_x86_64.tar.gz
          tar -xvf swag_1.7.0_Linux_x86_64.tar.gz
          ./swag init -g apiHandlers/router.go --output docs
          rm swag
          rm swag_1.7.0_Linux_x86_64.tar.gz

      - name: Build & Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ${{ secrets.DOCKER_USERNAME }}evolza/message_and_inquiry_management
          tags: latest
          registry: docker.io
          username: ${{ secrets.CGAAS_DOCKER_USERNAME }}
          password: ${{ secrets.CGAAS_DOCKER_ACCESSCODE }}

      - name: Configure Nginx and Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          script: |
            cd /root/
            bash ./samplescript2 real.demo.cgaas.ai 5000 80 real-estate-2 chamixth real-estate-website
