name: message_and_inquiry_management

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build & Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/real-estate-website-2
          tags: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up environment variables
        run: |
          # Fetch the contents of the .env file from the GitHub repository
          ENV_FILE_CONTENTS=$(curl -sL "https://github.com/Chamixth/real-estate-website-2/blob/main/.env")
          
          # Store the contents in environment variables
          export $(echo "$ENV_FILE_CONTENTS" | xargs)

      - name: Configure Nginx and Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          script: |
            cd /root/
            ls
            bash ./samplescript3.sh 
